Implement apiBody and apiQuery tags
apidoc/apidoc-core pull request #104
Opened 2020-09-24 19:29 UTC by SWheeler17

This is for issue #24 which suggested an apiBody and apiQuery be created instead of using (the general tag) apiParam.

2020-09-25 12:59 UTC, NicolasCARPi commented
Hello,

Thank you for your contribution. It would be great if you could add some tests.

Also, the documentation needs to be modified to reflect the changes and the new available params.

Finally, it looks like you basically took the code from api_param and copy/pasted it to create the two new types. Isn't it possible to reduce this duplication in one way or another?

2020-09-28 22:20 UTC, SWheeler17 commented
@NicolasCARPi where is the documentation? I was not able to find it in the project, though I may have been looking in the wrong place for it.

2020-09-28 22:37 UTC, NicolasCARPi commented
Here you go: https://github.com/apidoc/apidocjs.com

2020-09-29 00:21 UTC, SWheeler17 commented
@NicolasCARPi I am working on updating the documentation. When I make a PR, do you want me to reference this PR (with a URL or something to that extent)?

2020-10-02 09:39 UTC, NicolasCARPi commented
@SWheeler17 This is already much better. I'll merge this after you propose a documentation change. It's important to keep the documentation in sync with the code, and because you are adding functionality, it is also your responsability to modify the documentation to indicate the usage of such params and in which case they are useful.

2020-10-02 22:03 UTC, SWheeler17 commented
Ok, @NicolasCARPi how do you want me to link this PR to the PR on the documentation PR? I was going to add the link of this PR to that (eventual) PR unless you want me to do something else.

2020-10-02 22:15 UTC, NicolasCARPi commented
Whatever works for you!

2020-10-02 22:42 UTC, SWheeler17 commented
Documentation PR: https://github.com/apidoc/apidocjs.com/pull/34

2020-10-07 14:49 UTC, NicolasCARPi commented
Please ping me if this has not been reviewed in a week.

2020-10-19 22:00 UTC, SWheeler17 commented
@NicolasCARPi this has not been merged and does not appear to have been reviewed either.

2020-10-21 12:24 UTC, tommy87 requested changes

2020-10-21 12:24 UTC, tommy87 commented on lib/workers/api_body_title.js
> +var semver = require('semver');
This whole file is mostly a copy of "api_param_title.js". You should base on the existing code (maybe including api_param_title.js) and apply only small changes. 

Having the same code 3 is very bad

2020-10-21 12:24 UTC, tommy87 commented on lib/workers/api_query_title.js
> +var semver = require('semver');
This whole file is mostly a copy of "api_param_title.js". You should base on the existing code (maybe including api_param_title.js) and apply only small changes. 

Having the same code 3 is very bad

2020-10-21 12:49 UTC, tommy87 commented
Here is a good example https://github.com/apidoc/apidoc-core/blob/master/lib/workers/api_success_title.js

2020-10-21 21:30 UTC, SWheeler17 commented
@tommy87 I updated the two files you commented on, addressing your comments. Please review it again.

2020-10-22 07:01 UTC, tommy87 approved these changes
Looks much better, but i still need to run tests.

@rottmann @NicolasCARPi 
is there any chance to enable CI / Actions in this project which run the tests automatically?

2020-10-22 08:49 UTC, NicolasCARPi commented
@tommy87 Yes sure! Github actions or CircleCI.

2020-10-22 14:05 UTC, tommy87 commented
@NicolasCARPi ah i thought it must be enabled first, but when it is similar to gitlab i could create a simple test in the next days

2020-10-22 15:29 UTC, NicolasCARPi commented
I would favor github actions as they do not require a third party account/access.

There used to be Travis CI IIRC on this repo. But maybe @rottmann pulled the plug.

2020-10-23 16:34 UTC, tommy87 commented
@SWheeler17 i have create some CI actions on the dev branch. Could you rebase your branch so that the tests are triggered

@NicolasCARPi shouldnt the dokumentation be updated before pulling?

2020-10-23 23:01 UTC, SWheeler17 commented
@tommy87 I have rebased and the tests seem to have run successfully. The documentation PR is here: https://github.com/apidoc/apidocjs.com/pull/34 (for future reference).

2020-10-24 05:13 UTC, tommy87 requested changes
Just correct the name and then everythign should be fine

2020-10-24 05:13 UTC, tommy87 commented on test/parser_api_body_test.js
> +describe('Parser: apiParam', function() {
This is the apiBody test and not the apiParam test

2020-10-24 05:16 UTC, SWheeler17 commented
Oops, fixed @tommy87, my bad.

2020-10-24 05:17 UTC, tommy87 approved these changes
@NicolasCARPi i think it is ready for pulling

2020-10-29 15:15 UTC, SWheeler17 commented
What is the likelihood of this PR being pulled within the next few days?

2020-10-29 15:27 UTC, merged

2020-10-29 15:28 UTC, NicolasCARPi commented
> What is the likelihood of this PR being pulled within the next few days?

100% :p