expose parseSource
apidoc/apidoc-core pull request #106
Opened 2020-10-09 01:23 UTC by woodgear

2020-10-09 07:49 UTC, NicolasCARPi commented
Can you please explain the change with words?

2020-10-09 13:30 UTC, woodgear commented
expose a mehod named parseSource，that accept the sourcecode string as argument，since that we could use this api，the parse our code more programly。

2020-10-19 11:18 UTC, tommy87 requested changes
Please also write a test in `apidoc-core/test/` that show that loading from file and loading from source are working at the same time

2020-10-19 11:18 UTC, tommy87 commented on lib/index.js
> +
Why you moved the logger above. I assume it has something todo with issue #105. But the you should create an own merge request for this.

2020-10-19 11:18 UTC, tommy87 commented on lib/index.js
> +        app.filter = filter;
Until here your whole code is the same as in `function parse(options) { ` So you should put this parts in an extra function or combine both functions to one. Doubling code is never a good idea

2020-10-20 15:52 UTC, woodgear commented
@tommy87 @NicolasCARPi  i have updated this pr by review.

2020-10-21 11:32 UTC, tommy87 approved these changes
Looks good for me, but the code should be tested before merging.

2020-10-21 12:49 UTC, woodgear commented
i glad to add some test either,but i thought i need some help for that. for example where should i add the test to? [here](https://github.com/apidoc/apidoc-core/blob/8ead7e7ed9faa13c4f870a82ab22e0d17bc76561/test/apidoc_test.js#L100)?

2020-10-21 12:54 UTC, tommy87 commented
Just create a new file [here](https://github.com/apidoc/apidoc-core/blob/8ead7e7ed9faa13c4f870a82ab22e0d17bc76561/test/parser_api_description_test.js) is good and short example how you could do that

2020-10-22 13:20 UTC, woodgear commented
@tommy87  @NicolasCARPi  add some test for parseSource

2020-10-23 16:38 UTC, tommy87 commented
@woodgear i have add some CI action to the dev branch. Please rebase your code, so that the tests are triggered. Oh and please merge into the dev branch, not in the master branch.

2020-10-27 16:55 UTC, closed without merging

2020-10-27 16:58 UTC, woodgear commented
created a new pr in #109